### ISSUE TITLE
Allow user to be able to repay borrowed positions with aTokens

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#114]
- Currently the user can repay borrowed positions either from their **wallet balance** OR their **current collateral**. A nice feature would be if they could repay their debt with some of their aTokens. Currently when u borrow Dai u can only repay with Dai. For next iteration if borrow with aDai you can also repay with aDai. FE repayment view should show the user has an aDai balance. They should be able to repay with dai OR aDai. 

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Jobs to be done

- When I have positions borrowed on Aave, I want to the ability repay in atokens, so I don\t have to use my other assets.

- When I am have borrowed positions in Aave, I want to be able to know my options for repayment, so I know that I am aware of how I can repay.

- When I have positions borrowed in Aave,  if i dont have any atokens, I should not be able to see this option available it should be disabled.

- When i want to repay, I want to know the values of my positions and the outstanding repayment balance, so I can chose which currencies I can repay in. 

### Design Specifications
https://www.figma.com/file/R3a0OuN6jKoLnAo5mvAx6M/V3%3A-Repay-with-aTokens?node-id=9%3A9

**Comment by MareskoZ** [comment]
**BUG1:** 
repay confirmation form looks out of design 

![2021-12-15 13_55_53-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146175367-2db9c1ca-2b65-47ad-a7ab-a26ef24cdf64.png)

for all other actions where we should make approval before action we a using 2stpes form here isn't

looks like that we should change this form to the usual 2 step approval the form

**Comment by MareskoZ** [comment]
Repay by aTokens not available anymore

Steps:
1. open repay 
2. select aToken
3. move to a confirmation page

Result:
- we get a confirmation page with the usual token 

![aRepay](https://user-images.githubusercontent.com/18032275/147255414-52d7c79c-7a37-4d7d-aa37-cc64f54253f3.gif)
