### ISSUE TITLE
Polygon WMATIC Rewards Displayed Wrong

### ISSUE THREAD

**Issue by njohnst** [aave/aave-ui#126]
## Prerequisites

- [x ] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When trying to flashswap collateral during 
network congestion, I created multiple transactions that were pending.
(Polygon/MATIC network)

After finally resolving the issue, and getting my desired allocation of collateral,
my WMATIC rewards were displayed as +178 WMATIC.

When I claimed rewards, I received close to what I believe to be the correct amount (0.99WMATIC).

## Expected Behavior 🤔

The WMATIC rewards balance should have been displayed correctly as lower
(<1 WMATIC), but they were really high!

## Steps to Reproduce 🕹

Steps:

0. Polygon/MATIC network congested / slow.
1. Attempt to swap USDC for DAI with slippage set to 0%
2. Try to resubmit the transaction multiple times, and it's not going through, even when raising gas to speed it up
3. Cancel the transactions, and try manually withdrawing USDC collateral
4. WMATIC is displayed incorrectly as a really high number ! (Maybe related to flashloans, and balance being temporarily inflated ?)

## Your Environment 🌎

<details>
  <summary>info</summary>

```
  browser: Firefox / METAMASK
  os: win10
  vpn: NO
```

Console errors:
```
[error]: ...
```

</details>

**Comment by aschmidt20** [comment]
Several people have reported this on Polygon and Avalanche, it appears to happen immediately after a deposit or borrow in normal mode and is resolved with a page refresh

**Comment by sakulstra** [comment]
Should be reaolved
