### ISSUE TITLE
Add IPFS Pin to Crust Network

### ISSUE THREAD

**Issue by yyd106** [aave/aave-ui#145]
- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Since AAVE already deploy the frontend to IPFS(Pinata), we proposed PR #122  to help AAVE's frontend to extend more replicas in a decentralized way.

Crust Network is an incentive protocol beyond IPFS, now it has 7000+ IPFS nodes and over 2000+ PB IPFS storage volumes around the world. It can help AAVE's frontend unstoppable and make it more decentralized!

## Examples 🌈

1. [Uniswap](https://app.uniswap.org/#/swap) is using the Github Action -- `ipfs-crust-action` to Pin the Dapp to IPFS in Github Action way. Here is the code ref(https://github.com/Uniswap/interface/blob/main/.github/workflows/release.yaml#L58-L64), and here is the issue introduced why Uniswap need Crust([CI] Uniswap Interface decentralized IPFS pin Uniswap/interface#1339)

2. [Polkadot Apps](https://polkadot.js.org/apps/) is using `crust-pin` node package in the CD process, here is the code ref(https://github.com/polkadot-js/apps/blob/master/scripts/ipfsUpload.mjs#L94-L99)

## Motivation 🔦

1. High Availability: frontend files will be distributed to 30+ IPFS nodes in Crust Network;
2. Decentralization: all the nodes in Crust Network are distributed and decentralized;

**Comment by sakulstra** [comment]
@yyd106 thx for the issue.
I think it's fair to give it a shot.
Will refactor the pipeline to seperate cf and pinata so the crust pinning can happen before the cf update.
Will let you know in case i need help.
