### ISSUE TITLE
Empty screen on staking page

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#146]
## Empty screen on staking page for an unauthorized user 

if we open the staking page as unauthorized user  we get a blank screen 

![2021-11-11 14_55_18-Ubuntu AAVE - VMware Workstation 16 Player (Non-commercial use only)](https://user-images.githubusercontent.com/18032275/141294573-75996675-aadf-4ef2-aeeb-52b19b8e775b.png)

**Comment by sakulstra** [comment]
@MareskoZ should be resolved right? if yes plz close

**Comment by MareskoZ** [comment]
fixed
