### ISSUE TITLE
Allow users to enable Efficiency Mode

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#170]
If you borrow stablecoin assets of the same category. Currently in v2 we can only get 80% borrowing power. In v3 you can borrow up to 98%. The user needs to toggle if they want to enter into efficiency mode or not. The user needs to limit himself to a certain category of assets being borrowed(For example stablecoins). 

They should be able to enable efficiency mode of ONLY 1 category at a time. If user activates efficiency mode and choses stablecoins. Deposit usdc and borrow dai USDC will have 99% borrowing power instead of 80%.

To learn more about v3 features see the governance proposal: https://governance.aave.com/t/introducing-aave-v3/6035  

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

- When I want to borrow more of a collateralized asset, I should be able to trigger emode, so I can borrow more of a an asset(Up to 99%).
- When I want to enter efficiency mode, I should know the reason why I can only select one category, so that I am aware of how this works
- When I enter efficiency mode, I should be able to select the category of coins that I want to select, so that I can borrow an asset of that category.
## Examples 🌈

Design Specifications: https://www.figma.com/file/SRPFQfp6ta3lkWqN0HreWE/V3%3A-E-Mode

Prototype: https://www.figma.com/proto/SRPFQfp6ta3lkWqN0HreWE/V3%3A-E-Mode?page-id=623%3A1551&node-id=623%3A1554&viewport=241%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=623%3A1554

**Comment by defispartan** [comment]
Frontend:
- My Dashboard: always display eMode tooltip and button to pull up eMode menu
    - Display off icon, or eModeLabel if active
- eModeMenu:
   - If Active: Display active eModeLabel and button to disable
   - If Inactive: Allow user to select category (or disable selection) based on currently deposited and borrowed assets
 - Borrow Screen: Display active eModeLabel and only enable borrowing of assets in the eModeCategory if eMode enabled

Utilities:
- Add parameter to formatUserSummaryData() to specify active eMode category. This will specify the liquidation threshold / LTV to use for each reserve in the user calculations 
- Modify generateRawUserSummary data to use the active user eMode category + reserve eMode data to calculate the correct healthFactor and availableBorrows

Questions:
- Where is the eMode liquidation threshold / LTV displayed on the frontend? Or is this only used for the user calculations?
- What is the eModePriceSource variable from the UiPoolDataProvider used for?
- The users active eModeCategory is not returned by the UiPoolDataProvider so where is this being fetched from?

**Comment by foodaka** [comment]
@defispartan let me know if you think we should break this issue into multiple issues :)

**Comment by sendra** [comment]
Regarding the users active eModeCategory, we are returning userEmodeCategoryId from the UiPoolDataProvider. This field indicates the eModeCategory the user is in. We get this from the method: getUserReservesData

**Comment by defispartan** [comment]
@foodaka I think it makes sense to still keep it as one issue, it's almost finished anyways :)

A few questions I had when working through this for you + design team:
- Once there's multiple eMode options added (stablecoins, eth, btc), where should the toggle be to select the one you want to enable, on the dashboard or in the enable/disable modal?
- There's a few Learn More buttons on various pages, is this going to be a tooltip or link to an external page?
- Should any changes be made to the reserve overview page to display the eMode LTV/liquidation threshold/liquidation bonus?

**Comment by foodaka** [comment]
@defispartan for the learn more I assume there will be some added to the FAQ. Ive created a seperate issue for that here https://github.com/aave/aave-ui/issues/190

**Comment by defispartan** [comment]
> @defispartan for the multiple eMode options I think @iamanastasia has this scenario in the design. I guess in the future if the user needs to select between 5 or more options we could change this to a dropdown, but for now i think it will only be able to use stablecoins from governance.
> 
> ![Screen Shot 2021-11-24 at 9 10 12 AM](https://user-images.githubusercontent.com/8342048/143208608-09226e75-7bbf-4778-91df-55462ab483c6.png)

Sweet! Since stablecoin eMode will be the only one available at first, I think it makes sense to create a separate issue to create this page and add support for multiple eModes

**Comment by foodaka** [comment]
Closing out as per https://github.com/aave/aave-ui/pull/189
