### ISSUE TITLE
Users should be able to switch to the correct network via ui

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-ui#175]
- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Currently the ui only allows switching to polygon/avalanche networks. For all the other networks you manually have to change the network in your wallet.

https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods allows us switching to any arbitrary chain.

## Examples 🌈
When your on polygon network and you want to deposit withdraw sth on mainnet you have to manually change your network.

## Motivation 🔦
Improved ux

**Comment by MareskoZ** [comment]
QC passed
