### ISSUE TITLE
Aave snapshot space should be linked from the governance

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-ui#178]
## Summary 💡

https://snapshot.org/#/aave.eth should be linked from the ui

**Comment by foodaka** [comment]
@sakulstra should this be from the governance or where do you suggest we put this information?

**Comment by foodaka** [comment]
How about here? @iamanastasia @sakulstra 
![Screen Shot 2021-12-13 at 10 19 52 AM](https://user-images.githubusercontent.com/8342048/145794870-3db8a582-fe44-4268-af04-91bcb44cc9d3.png)
