### ISSUE TITLE
Aave dropdown shows ethereum mainnet mainnet

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#187]
When connecting a wallet, it shows "ethereum mainnet mainnet" instead of "ethereum mainnet"

## Prerequisites

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

![Image Pasted at 2021-11-22 22-34](https://user-images.githubusercontent.com/8342048/142912512-6e969e10-4917-44e3-a841-852771471851.png)

## Expected Behavior 🤔

"Ethereum Mainnet"

## Steps to Reproduce 🕹

Steps:

1. Go to connect wallet page
2. Click dropdown
3.See text
4.

## Your Environment 🌎

<details>
  <summary>info</summary>

```
  browser: chrome
  os: win10
  vpn: yes
```

Console errors:
```
[error]: ...
```

</details>

**Comment by sakulstra** [comment]
The pr in #188 proposes to also completely remove the mainnet wording for non ethereum assets:
![image](https://user-images.githubusercontent.com/4396533/143027200-ec8151ed-605c-42da-88e5-abd7419d059e.png)
