### ISSUE TITLE
Add vAPR as an indicator

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#191]
Confexfinance adds a field for vAPR on their pools. This indicates to the user "variable annual percentage rate". This indicates the interest you would earn on your deposits for an entire year. Its variable because it depends on the price of the assets you deposit, the price of the assets you are rewarded with, and the current reward rates.

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

See example
![Screen Shot 2021-11-25 at 12 30 10 PM](https://user-images.githubusercontent.com/8342048/143442171-c3a6e4ab-b331-4de2-aef8-879b60773aaa.png)

https://www.convexfinance.com/stake

**Comment by sakulstra** [comment]
what's the difference to 
![image](https://user-images.githubusercontent.com/4396533/143835606-8bc7f617-71d4-4e60-8976-3e5b458448f2.png) ?

Are you missing the explanation or am i misunderstanding the request?

**Comment by foodaka** [comment]
Yeah im not convinced on this I think for now APY is ok
