### ISSUE TITLE
Update client with logic to support new v3 UiIncentiveDataProvider for multi incentives

### ISSUE THREAD

**Issue by sendra** [aave/aave-ui#192]

**Comment by MareskoZ** [comment]
**Claim all rewards doesn't work** 

Steps:
1. make a deposit/borrow  to collect a few types of rewards
2. try to claim all rewards together 



result:
- tx failed 

![multi-claim](https://user-images.githubusercontent.com/18032275/146361418-d337cb34-3936-4705-abd2-26f6adeb3f8d.gif)

**Comment by MareskoZ** [comment]
looks fine for me
