### ISSUE TITLE
Repay by aTokens bugs  

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#242]
**BUG1:** 
repay confirmation form looks out of design 

![2021-12-15 13_55_53-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146175367-2db9c1ca-2b65-47ad-a7ab-a26ef24cdf64.png)

for all other actions where we should make approval before action we a using 2stpes form here isn't

looks like that we should change this form to the usual 2 step approval the form 

**BUG2:** 
when we try to permit to repay by Atokens we didn't get request for approve and get wrong screen 
![2021-12-15 15_21_15-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146185952-1fc57192-3c03-44b9-8e7e-f40de9994327.png)

steps:
1. open repay view
2. choose repay by aTokens
3. try to permit

result:
- no request to confirm
- gray screen

_Originally posted by @MareskoZ in https://github.com/aave/aave-ui/issues/114#issuecomment-994682703_

**Comment by sakulstra** [comment]
should work again now, pol fixed it
