### ISSUE TITLE
**Claim all rewards doesn't work**

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#245]
**Claim all rewards doesn't work** 

Steps:
1. make a deposit/borrow  to collect a few types of rewards
2. try to claim all rewards together 

result:
- tx failed 

![multi-claim](https://user-images.githubusercontent.com/18032275/146361418-d337cb34-3936-4705-abd2-26f6adeb3f8d.gif)

```
cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":4666,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x4e487b710000000000000000000000000000000000000000000000000000000000000032\"}}\n","error":{"code":3,"data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000032"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0x0\",\"from\":\"0xca0e8f557ea98f950029a41d74f16dd76648b1f1\",\"to\":\"0xf0a070fc39d70fbb970fa0ffb5d3a026b28cc4ac\",\"data\":\"0xbb492bf50000000000000000000000000000000000000000000000000000000000000040000000000000000000000000ca0e8f557ea98f950029a41d74f16dd76648b1f1000000000000000000000000000000000000000000000000000000000000000300000000000000000000000059997a5ad47c5335dec0dbf6420c93494a37f6be000000000000000000000000e42ff78eba6a408ec7d141386b050d25df02686d000000000000000000000000f340647afffd6b2013d6514a49075307e767f213\"}],\"id\":4666,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rinkeby.arbitrum.io/rpc"}, method="estimateGas", transaction={"from":"0xCA0E8F557ea98f950029A41D74F16DD76648B1F1","to":"0xF0A070Fc39d70FBB970Fa0fFb5D3a026b28CC4aC","value":{"type":"BigNumber","hex":"0x00"},"data":"0xbb492bf50000000000000000000000000000000000000000000000000000000000000040000000000000000000000000ca0e8f557ea98f950029a41d74f16dd76648b1f1000000000000000000000000000000000000000000000000000000000000000300000000000000000000000059997a5ad47c5335dec0dbf6420c93494a37f6be000000000000000000000000e42ff78eba6a408ec7d141386b050d25df02686d000000000000000000000000f340647afffd6b2013d6514a49075307e767f213","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.1)
```

_Originally posted by @MareskoZ in https://github.com/aave/aave-ui/issues/192#issuecomment-995693943_

**Comment by foodaka** [comment]
Same issue from me as well
![Screen Shot 2021-12-16 at 12 51 10 PM](https://user-images.githubusercontent.com/8342048/146375698-8e7a8430-9882-4600-929e-0dcb72fd0ed3.png)

**Comment by MareskoZ** [comment]
claim was fixed but there is one additional thing

on the confirmation page, we have `Total worth` - which have dynamic calculation and in a case, when we claim reward and stay on the confirmation page, we see that:
- total worth - go down and then grow up
- claim amounts - stay stable

![2021-12-23 17_17_03-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/147253191-0a982095-796c-4724-8efe-9f768ccbbf87.png)

maybe it will be better to fix `Total worth` after the claim reward? 

also same actual for separate claim 

CC @foodaka @sendra

**Comment by foodaka** [comment]
@sendra @MareskoZ 
- I think it makes sense that **after** the claim all of these numbers are fixed. Because this page shows a confirmation of the information the user just claimed

**Comment by sakulstra** [comment]
fixed in https://github.com/aave/aave-ui/pull/279/commits/364d73c4a49593b36e779cf859adb2fb28381c29

**Comment by foodaka** [comment]
@MareskoZ can you confirm on branch https://github.com/aave/aave-ui/compare/feat/262-dashboard-supply and we can close it out :)

**Comment by MareskoZ** [comment]
fixed
