### ISSUE TITLE
Borrow Power shows 100% when no assets are supplied as collateral

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#247]
When you supply assets and disable collateral the borrowing power used shows 100%. Should we hide this information or show a different message in this scenario?

![Screen Shot 2021-12-16 at 11 31 40 AM](https://user-images.githubusercontent.com/8342048/146375596-318e50fc-8478-438c-814b-206d2a0a6ab6.png)

## Prerequisites

- [ ] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>info</summary>

```
  browser: chrome
  os: win10
  vpn: yes
```

Console errors:
```
[error]: ...
```

</details>

**Comment by sakulstra** [comment]
@iamanastasia technically this is correct as `0 available means 100% used`, in this special case it's just 0 of 0... might make sense to just not show the bar in that case or show a message saying no collateral? idk

**Comment by iamanastasia** [comment]
@sakulstra But how it can be valid if user has Borrowed amount = 0? Should we add borrowed value check to the logic? If 0 then it's 0.

**Comment by sakulstra** [comment]
should be resolved and now show 0 %

**Comment by MareskoZ** [comment]
done
