### ISSUE TITLE
Switching to E-mode Activation - wrong Health factor

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#248]
on the confirmation screen to turn on/off E-mode, the new health factor is not calculated correctly, it's 0.00 every time 

![2021-12-16 15_52_33-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146376879-aaf9919c-0e1e-4fe1-b011-f707c63dc01a.png)

**Comment by sakulstra** [comment]
should be working again

**Comment by MareskoZ** [comment]
fixed
