### ISSUE TITLE
show all reserves on dashboard that the user has in wallet balance

### ISSUE THREAD

**Issue by sendra** [aave/aave-ui#262]
As a User I want to see all the reserves I am able to deposit into from the dashboard view.

Technical:
Move to the dashboard all the logic from the Deposit page, so when I enter into my dashboard I see there all the reserves i have deposited previously (same as current dashboard vehaviour) and also all the other reserves that I have tokens in my wallet and I could deposit into (accounting with v3 logic (caps etc)) (adding supply button to the reserve row, the same as already deposited reserves)

This way I will no longer need the deposit page, and i will be able to manage all my deposits from the dashboard

**Comment by foodaka** [comment]
I guess one downside is that you dont see which tokens are available outside of your wallet in this scenario

**Comment by foodaka** [comment]
however that i think might be ok because we can separate out markets with dashboard

**Comment by foodaka** [comment]
waiting on final confirmation from design specification
