### ISSUE TITLE
Update Reserves row to add + information on dashboard view

### ISSUE THREAD

**Issue by sendra** [aave/aave-ui#264]
As we will no longer have the borrow / supply page, I as a user, want to be able to see extended information on the reserves before deciding if I want to supply or borrow.

I want to click on the + sign on the reserve row (TBD) so the row gets extended with the information seen on the Supply / Borrow page of the token in question. This way I will be able to see (If i want) all the token info in the reserve view.

![image](https://user-images.githubusercontent.com/6848271/146800351-f62173be-deb5-47fb-87c3-3253756a6635.png)

**Comment by foodaka** [comment]
We need to decide which information of this we want to continue to show and where. I think we should discuss this with @iamanastasia

**Comment by foodaka** [comment]
I think that we can capture that information in the popup @sendra when user wants to supply or borrow.
