### ISSUE TITLE
Move Deposit flow to a modal started in dashboard

### ISSUE THREAD

**Issue by sendra** [aave/aave-ui#265]
I as a User want to be able to supply directly from the dashboard, without the need to leave the dashboard view.

Technical:
Move the flow of the Supply view after we click on a Reserve to a modal that will appear in the dashboard, when we click on the Supply button on the Reserve row of our choosing.

**Comment by foodaka** [comment]
Just a note on design: Should we have 1 dialog that allows you to either deposit or borrow with a tab OR just two separate dialogs.

Pro with tab - you can deposit or borrow within the same dialog.
con - likely more complex, you dont need to have both likely (you wanna either deposit or borrow)

**Comment by foodaka** [comment]
<img width="380" alt="Screen Shot 2021-12-21 at 8 05 05 AM" src="https://user-images.githubusercontent.com/8342048/146934879-47d9cfc2-2343-4672-b990-ed112a7d593a.png">
