### ISSUE TITLE
Health factor on repay page doesn't work

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#273]
Calculation of health factor on repaying page doesn't work, new health factor every time = 2

![2021-12-21 12_18_40-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146904769-ab7c4c01-a138-4070-bb01-fbefb4046fd2.png)

Calculating of new health factor shod depends from the amount for repaying in input

**Comment by sakulstra** [comment]
should work now

**Comment by MareskoZ** [comment]
qc Passed
