### ISSUE TITLE
Submit tx with wrong network - wrong error message

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#275]
Case:
1. switch to Eth mainnet network on MM
2. open any action on the confirmation page for arbitrum 
3. try to submit tx

Bug1: wrong error text
![2021-12-21 12_40_59-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146907818-1113ece0-80ba-47ef-aa5c-9e7734b09fea.png)

Bug2:
should be able to switch  to the correct network via UI

**Comment by sakulstra** [comment]
should be fixed

**Comment by MareskoZ** [comment]
fixed
