### ISSUE TITLE
Wallet connection - list of problems 

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#276]
Problem1:
Steps:
1. open app
2. switch to polygon market
3. open wallet connection popup

result:
- `Select preferred network`- stay default and not depend on the market which user chose (in case of V3 it's kovan )
![2021-12-21 13_07_18-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/146911705-350a21c3-dc48-4568-a193-a0483fe49bc0.png)

Problem2:
Steps:
1. choose mainnet network
2. open app on arbitrum market 
3. open connection popup and choose arbitrum market in the dropdown 
4. try to connect 

result:
- page just reloaded without successful connection
- also there is no error that could notify that customer should switch network manually 

![wallet-connect](https://user-images.githubusercontent.com/18032275/146912889-80874f1e-6600-4ba4-bc17-5052c1ac8330.gif)

**Comment by sakulstra** [comment]
should be fixed on latest arbitrum-clean

**Comment by foodaka** [comment]
@sakulstra does it include `Select preferred network- stay default and not depend on the market which user chose (in case of V3 it's kovan )``

**Comment by sakulstra** [comment]
> @sakulstra does it include `Select preferred network- stay default and not depend on the market which user chose (in case of V3 it's kovan )``

No i initially didn't understand that point. Now i do and here's a fix for it, plz review: https://github.com/aave/aave-ui/pull/280

**Comment by MareskoZ** [comment]
looks good

qc Passed
