### ISSUE TITLE
E-mode borrow - search by list

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#285]
If E-mode enabled search by coins doesn't work on borrow page 

![2021-12-22 17_07_14-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/147105733-754f4bff-eaaf-4afa-a812-d657b294e79a.png)

also same happened for borrow page when isolated mode ON
![2021-12-22 17_30_23-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/147116238-fee5602b-f972-4e08-99db-00ab9662dae4.png)

**Comment by foodaka** [comment]
Do we need search in this scenario as there will only be a few assets in each category?

**Comment by MareskoZ** [comment]
> 

I think that now, better to remove the search for these cases

**Comment by sendra** [comment]
This issue i think its no longer relevant, as we are moving the the borrow list to the dashboard, and I think we are also removing the search.
