### ISSUE TITLE
Repay by aTokens not available anymore

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#291]
Repay by aTokens not available anymore

Steps:
1. open repay 
2. select aToken
3. move to a confirmation page

Result:
- we get a confirmation page with the usual token 

![aRepay](https://user-images.githubusercontent.com/18032275/147255414-52d7c79c-7a37-4d7d-aa37-cc64f54253f3.gif)

_Originally posted by @MareskoZ in https://github.com/aave/aave-ui/issues/114#issuecomment-1000348461_

**Comment by sakulstra** [comment]
it is, just the symbol was wrong - should be fixed on latest version

**Comment by foodaka** [comment]
Agree i think its now fixed, can you confirm @MareskoZ can then close out?

![Screen Shot 2022-01-04 at 11 32 59 AM](https://user-images.githubusercontent.com/8342048/148053106-449ade05-4a35-4a73-849b-58ad579c2599.png)
