### ISSUE TITLE
V3 Dashboard 

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#292]
From yesterdays meeting we need to polish some of the new dashboard UI.

- ~~Remove deposit and borrow white boxes when there are no positions.~~
- ~~Update text from "Assets to deposit" to "Available in your wallet"~~
- ~~Assets on borrow side should always be shown, regardless if you have a position or not.~~
- [x] Arbitrum banner should be able to be closed via "X". This should also be moved if possible 
- [x] add swap instead of deposit on the list of supply positions 
- [x] Show and hide should collapse
- [x] When an asset is partially deposited and partially in the wallet, we show it in both top and bottom part; the both part will only have withdraw/swap, the bottom part will only have deposit/details

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Examples 🌈

<img width="1423" alt="Screen Shot 2021-12-24 at 7 27 45 AM" src="https://user-images.githubusercontent.com/8342048/147353305-a7766ee8-4fb1-47c7-98e6-3694adf99a64.png">

- Note: Layout seemed broken with isolation mode and borrow positions
<img width="1436" alt="Screen Shot 2021-12-24 at 7 35 45 AM" src="https://user-images.githubusercontent.com/8342048/147353420-ecae2b8a-004c-4603-adc4-7c7537c5647e.png">

**Comment by iamanastasia** [comment]
1. We shouldn't remove deposit and borrow white boxes when there are no positions. It looks confusing. New user should see empty layout structure.

2. We can't update text from "Assets to deposit" to "Available in your wallet" — because those not assets in the wallet, but 'available assets' according to wallet+supply balance.

**Comment by foodaka** [comment]
Im confused about number 2. So the bottom left rows calculate
1) The balance of the wallet of the user
2) The balance also supplied in the protocol?

**Comment by iamanastasia** [comment]
@foodaka 
1. Wallet balance
2. Amount left in the supply cap.

So there might be 2 cases:
1. User's balance < Amount left in the supply cap
2. User's balance > Amount left in the supply cap

So in both cases we show 'Available to supply' with tooltip that says:
This is the total amount that you are able to supply to this reserve. You are able to supply your wallet balance up until the supply cap is reached.


There are assets that don't have Supply cap, but still. We need 1 text for all of them.

**Comment by The-3D** [comment]
1. The way it is shown right now is unpleasant design wise, and it takes up space that could be available for your assets that you can deposit. We either redesign it to be way more subtle and less intrusive, or we remove it altogether. As an example, compound has a similar design and it does not show anything as a placeholder for the supplied/borrowed assets, and it doesnt look confusing. The suppied/borrowed assets only appear when you actually supply/borrow, the placeholder doesnt add anything to the clarity of the feature in my opinion.
2. Available to deposit is confusing. "In your wallet" or "Wallet balance" or "Available in your wallet" are immediately understandable by the user. If the concern is the logic related to `max(what's in your wallet, what's left of the supply cap)` then we should probably handle this logic in the next step (when you click deposit, it shows how much you can actually supply taking into account the supply cap)

**Comment by sakulstra** [comment]
Iirc it was alsobdiscussed to add swap instead of deposit on the list of supply positions (missing in the list @foodaka )

**Comment by foodaka** [comment]
added thanks @sakulstra

**Comment by iamanastasia** [comment]
@The-3D here is the last design
![Frame 49229](https://user-images.githubusercontent.com/92739089/147447346-2176c1cc-7e3a-46aa-8811-79e8e57a6beb.png)
It looks more clear, but I highly recommend to show empty state of 'Your deposits/borrows' sections. So that we don't hide/show different sections out of nowhere. It can be helpful for new users, who just learns concept of lending/borrowing. 

@sakulstra If we show SWAP instead of deposit, then we need to show supplied asset in the 'available to supply' list as well

**Comment by iamanastasia** [comment]
Design with Swap
<img width="1168" alt="Screenshot 2021-12-27 at 12 56 02" src="https://user-images.githubusercontent.com/92739089/147449095-8079fd24-805e-4bc0-a635-6811b88bbfe3.png">

**Comment by sendra** [comment]
> @The-3D here is the last design ![Frame 49229](https://user-images.githubusercontent.com/92739089/147447346-2176c1cc-7e3a-46aa-8811-79e8e57a6beb.png) It looks more clear, but I highly recommend to show empty state of 'Your deposits/borrows' sections. So that we don't hide/show different sections out of nowhere. It can be helpful for new users, who just learns concept of lending/borrowing.
> 
> @sakulstra If we show SWAP instead of deposit, then we need to show supplied asset in the 'available to supply' list as well

yes, with adding the Swap button, the idea is also to show all assets on the assets to supply section

**Comment by foodaka** [comment]
Updated the specifications and status based on todays call

**Comment by foodaka** [comment]
I agree with @sendra - I think we should have a way to view
1) Assets in my wallet - this is done
2) Assets I could also possibly supply - These can be hidden with a toggle or checkbox. "Hide Zero Balances" or something
3) All assets I could possibly borrow - This is also done
