### ISSUE TITLE
Give the user the choice of wrapping/unwrapping

### ISSUE THREAD

**Issue by sendra** [aave/aave-ui#301]
### Technical background
Base network assets (eth/matic/avax) are not ERC20 so for interacting with the aave protocol they have to be wrapped.
This wrapping is done internally when you deposit such an asset.

While base assets have to be wrapped, it's also possible to deposit/withdraw & repay the **wrapped asset** instead of using the native one. This is not a limitation on the contracts but on the ui.

The user would have the choice to:
- deposit weth or eth
- withdraw as weth or eth
- repay will weth or eth

The motivation for using weth over eth would be that weth interactions are less gas intensive & weth being used by most other protocols, so you save unwrapping/wrapping again.

The motivation for using eth would be that you can use it for gas.

Current v3 solution:
You can deposit both assets (one row for each)

**Comment by foodaka** [comment]
We have decided to push this outside the scope of v3
