### ISSUE TITLE
FTM icon and coin name not visible on the fantom test net

### ISSUE THREAD

**Issue by AdamGencel** [aave/aave-ui#368]
<img width="1257" alt="Screenshot 2022-01-25 at 14 54 02" src="https://user-images.githubusercontent.com/42351914/150994877-cb270510-79e9-4b5c-9cf5-4b12753cd212.png">
<img width="1262" alt="Screenshot 2022-01-25 at 14 53 08" src="https://user-images.githubusercontent.com/42351914/150994924-4255dace-179b-474a-b928-dbd50f52752b.png">

**Comment by sakulstra** [comment]
- closed in #374
