### ISSUE TITLE
V3 Harmony market - ONE and WONE tokens doesn't have icon and name 

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#369]
missed name and icons for ONE token on Harmony market 

![2022-01-25 17_39_12-Aave - Open Source Liquidity Protocol](https://user-images.githubusercontent.com/18032275/150997677-5b70225f-9b63-4d37-a4ee-4991334112d9.png)

**Comment by sakulstra** [comment]
- closed in #375
