### ISSUE TITLE
Borrowing USDT does not allow to borrow with stable apy 

### ISSUE THREAD

**Issue by AdamGencel** [aave/aave-ui#371]
**At the moment when trying to borrow 900 USDT with a deposit of 3000USDT** 
<img width="604" alt="Screenshot 2022-01-25 at 16 29 22" src="https://user-images.githubusercontent.com/42351914/151011882-ee8e8548-6477-4939-9ed6-744dc6c0be67.png">

There is only variable APY available:
 
<img width="546" alt="Screenshot 2022-01-25 at 16 29 27" src="https://user-images.githubusercontent.com/42351914/151012022-39f897ab-83e0-4898-94f1-93f390bb7d3f.png">

However after it is borrowed, I am able to change the borrowing from variable to stable 

<img width="1233" alt="Screenshot 2022-01-25 at 16 29 51" src="https://user-images.githubusercontent.com/42351914/151012131-280760b8-1d0d-4ab2-b198-cb009e0a2146.png">
<img width="536" alt="Screenshot 2022-01-25 at 16 30 01" src="https://user-images.githubusercontent.com/42351914/151012146-630c83e8-c60b-45b2-bf50-940c3026fcc9.png">
<img width="1251" alt="Screenshot 2022-01-25 at 16 59 46" src="https://user-images.githubusercontent.com/42351914/151012352-8e977f50-ebc8-4c5e-9f7a-b256cf6b8fab.png">

**Comment by defispartan** [comment]
Which network is this on? I wasn't able to replicate

**Comment by MareskoZ** [comment]
> Which network is this on? I wasn't able to replicate

it was Fantom 

but it's also actual for  Harmony

**Comment by sakulstra** [comment]
can reproduce, will have a look

**Comment by sakulstra** [comment]
@AdamGencel - was also confused by that, but that's actually how the protocol works.

In `ValidationLogic.validateBorrow` there's a check that disallows you borrowing more then 25% of total supply in stable rate - that's why you weren't able to borrow stable. That's some sort of gaming prevention on the contract level - once borrowed though you can switch the rate.
