### ISSUE TITLE
AAVE v2 market - supply values incorrect 

### ISSUE THREAD

**Issue by MareskoZ** [aave/aave-ui#375]
there is a lag with supply values

if we supply 30 USDT on the dashboard we see 29.9999
if 0.03 on the dashboard it will be  0.0299999

bug came from https://github.com/aave/aave-ui/pull/142 

now it's in https://github.com/aave/aave-ui/pull/154

![RENINT~2](https://user-images.githubusercontent.com/18032275/151077064-c40a6ccd-173c-4b6c-a40c-a228cfabcf25.PNG)

**Comment by MareskoZ** [comment]
is not actual

**Comment by Vandinew** [comment]
Am here
