### ISSUE TITLE
Not able to claim available reward

### ISSUE THREAD

**Issue by binoyda** [aave/aave-ui#381]
I am using Matic (Polygon POS) network, whenever I am trying to claim reward it showing following error

"1/2 Claim - Error
This transaction will fail. Please make sure you have enough MATIC and funds in the connected wallet for the transaction."

I can confirm that I have Matic token in that wallet and I am able to deposit to same AAVE wallet, yesterday for testing i deposited couple of MATIC and it showing in my deposit lists and today i deposited another .1 matic that also reflected in my deposit. However reward claim showing errors.

Please check

**Comment by sakulstra** [comment]
I think this is an issue with depleted rewards which should be fixed soonish.

**Comment by drewangell** [comment]
I am having the same problem.  Here's a video:  https://youtu.be/G3GwEifGwYc

**Comment by foodaka** [comment]
Yes, as the networks themselves set the reserves we are awaiting the top up

**Comment by foodaka** [comment]
Should be claimable now with polygon
