### ISSUE TITLE
Generic UI error when connected to unsupported network

### ISSUE THREAD

**Issue by pablofullana** [aave/aave-ui#438]
## Prerequisites

- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

As a User, when connected to an unsupported network I'm getting a generic UI error: 
> Application error: a client-side exception has occurred (see the browser console for more information).

Note: This only happens when browser viewport is wider than: 959px 🤔 

## Expected Behavior 🤔

As a User, I should not be getting this generic UI error message.

## Steps to Reproduce 🕹

Steps:

1. Connect MM to, let's say, ~BSC~ Gnosis Chain
2. Checkout error page

## Your Environment 🌎

<details>
  <summary>info</summary>

```
  browser: firefox
  os: macOS Monterey
  vpn: no
```

Console errors:
```
[error]: 

TypeError: f is undefined
    NextJS 16
[framework-bb5c596eafb42b22.js:1:82745](https://app.aave.com/_next/static/chunks/framework-bb5c596eafb42b22.js)
TypeError: f is undefined
    NextJS 16
[main-166ebf8347b95292.js:1:8368](https://app.aave.com/_next/static/chunks/main-166ebf8347b95292.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

</details>

**Comment by sakulstra** [comment]
this should be resolved, also wondering why you did report it on this repo - is there a wrong link somewhere? The correct one would have been here: https://github.com/aave/interface

**Comment by pablofullana** [comment]
Indeed, looks like solved!

Not sure how I got to this repo though.
