### ISSUE TITLE
Connecting to AAVE protocol should show ENS username

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#48]
Background:

A user provided feedback that we should show ENS username ~~and avatar~~ when users have connected their wallet in the dashboard. When users have connected their wallet it currently shows "Ethereum Mainnet 0xxx…..4545". If a user has an ENS domain that can resolve from being connected we should show that instead. For example if I own an ENS domain and I connect my wallet it should show defimark.eth ~~with my avata~~r pulled from ENS. See below the uniswap example.

ENS Specifications

https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182

Acceptance Criteria

When a user connects their wallet to the AAVE protocol we should show their ENS name ~~and avatar~~ if it exists.

If the user does not have an ENS registered show the default Ethereum Mainnet and their wallet address

**Comment by aschmidt20** [comment]
@foodaka Perhaps we should make the avatar a separate issue since the name part is done and handling all the different avatar uri types will take a bit more time

**Comment by foodaka** [comment]
@aschmidt20 added https://github.com/aave/aave-ui/issues/144 . Will bring in a design there and then we can add the profile picture. Great job btw
