### ISSUE TITLE
Something went wrong with mydashboard

### ISSUE THREAD

**Issue by amyflash** [aave/aave-ui#57]
Everytime i opened my dashboard on aave,it shows: Something went wrong
Please report the problem to our developer team so they can look into it.

My question matic address is 0x7DF95bB85f16602D9779972c8D3aD528bd1A9Fb0 
I try other address
, That is ok. Could someone tell me how to enter the normal dashboard?

**Comment by sakulstra** [comment]
closing due to staleness, feel free to reopen @amyflash in case that's still an issue.
