### ISSUE TITLE
Update the security page on the website to the latest design specifications

### ISSUE THREAD

**Issue by foodaka** [aave/aave-ui#72]
Background
We have been asked from legal and design to update our security page on the Aave website. Ive attached an image for reference

Acceptance Criteria
- Update the security page on the Aave website to the latest design specifications with the updated text.
- Figma Link: https://www.figma.com/file/IzJji5GA8FaRnGOt9Q9tYN/Website%3A-Security-Page?node-id=775%3A121
![security](https://user-images.githubusercontent.com/8342048/137929607-b31eff8a-b8b3-47b8-9957-70835ef25602.png)

**Comment by Argeare5** [comment]
@foodaka @sakulstra
PR: https://gitlab.com/aave-tech/aave-new-website/-/merge_requests/292
Link: https://website-update-security-page.aaw.fi/security

**Comment by Argeare5** [comment]
@foodaka fixed
